tap "homebrew/bundle"
tap "homebrew/core"
tap "rfidresearchgroup/proxmark3"
brew "git"
brew "pinentry-mac"
brew "gnupg"
brew "ykman"
brew "zsh"
brew "rfidresearchgroup/proxmark3/proxmark3", args: ["with-generic"]
