# Path to oh-my-zsh installation
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- see https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME=""

# Disable autoupdate because it is handled by git
DISABLE_AUTO_UPDATE=true

# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
plugins=(cp git screen)

# Enable Homebrew completions if installed
if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi

# Enable zsh-completions
FPATH="~/.oh-my-zsh/custom/plugins/zsh-completions/src:${FPATH}"

# Path modifications
export PATH

source $ZSH/oh-my-zsh.sh

autoload -Uz compinit
compinit